-- 書籍テーブル作成
CREATE TABLE IF NOT EXISTS books (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 書籍ID
                                     title VARCHAR(100) NOT NULL,                          -- タイトル
                                     price NUMERIC(10) CHECK (price >= 0),                 -- 価格
                                     author_id INT,                                        -- 著者ID
                                     publication_status BOOLEAN,                           -- 出版状況（true:公開/false:非公開）
                                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,       -- 作成日時（共通項目）
                                     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP        -- 更新日時（共通項目）
);

-- コメント
COMMENT ON COLUMN books.id IS '書籍ID';                          -- 書籍の一意な識別子
COMMENT ON COLUMN books.title IS 'タイトル';                     -- 書籍のタイトル
COMMENT ON COLUMN books.price IS '価格';                         -- 書籍の価格
COMMENT ON COLUMN books.author_id IS '著者ID';                  -- 書籍の著者を識別するためのID
COMMENT ON COLUMN books.publication_status IS '出版状況';       -- 書籍の出版状況（true:公開/false:非公開）
COMMENT ON COLUMN books.created_at IS '作成日';                 --  作成日時（共通項目）
COMMENT ON COLUMN books.updated_at IS '更新日';                  --  更新日時（共通項目）


-- 著者テーブル作成
CREATE TABLE IF NOT EXISTS author (
                                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 著者ID
                                      name VARCHAR(100) NOT NULL,                           -- 著者名
                                      birthDay DATE,                                        -- 生年月日
                                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,       -- 作成日時（共通項目）
                                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP        -- 更新日時（共通項目）
);

-- コメント
COMMENT ON COLUMN author.id IS '著者ID';                  -- 著者の一意な識別子
COMMENT ON COLUMN author.name IS '著者名';                -- 著者の名前
COMMENT ON COLUMN author.birthDay IS '生年月日';          -- 著者の生年月日
COMMENT ON COLUMN author.created_at IS '作成日';          -- 作成日時（共通項目）
COMMENT ON COLUMN author.updated_at IS '更新日';           -- 更新日時（共通項目）
